# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: 00 0 * * *
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: get latest tag
        id: var
        run: echo "tag=$(gh release view --repo tmux/tmux --jq .tagName --json tagName)" >> $GITHUB_OUTPUT
      - name: download tmux latest release
        run: gh release download ${{steps.var.outputs.tag}} --repo tmux/tmux
      - run: tar xfz ./tmux-${{steps.var.outputs.tag}}.tar.gz
      - run: mkdir ./dest
      - run: ./configure --prefix=./dest
        working-directory: ./tmux-${{steps.var.outputs.tag}}
      - run: make
        working-directory: ./tmux-${{steps.var.outputs.tag}}
      - run: make install
        working-directory: ./tmux-${{steps.var.outputs.tag}}
      - run: ls ./dest
